# Form implementation generated from reading ui file 'anewBecker.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 189)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"color:#fff;\n"
"font:11pt \"Helvetica\";\n"
"}\n"
"\n"
"QLabel {\n"
"background:transparent;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"                                 QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgba(22,22,22,100);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/*\n"
"VERTICAL\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:vertical {\n"
"    border-radius: 11px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    background-color: rgba(33,33,33,100);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgba(44,44,44,100);    \n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    border-radius: 11px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(22,22,22);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, \n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(22,22,22);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.beckPage = QtWidgets.QWidget()
        self.beckPage.setObjectName("beckPage")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.beckPage)
        self.gridLayout_24.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.beckPage)
        self.tabWidget.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(100,199,211);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(100,199,211);\n"
"    }\n"
"    \n"
"QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:1px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(11, 11))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setHorizontalSpacing(18)
        self.gridLayout_14.setVerticalSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.sadness = QtWidgets.QSlider(parent=self.frame_4)
        self.sadness.setMinimumSize(QtCore.QSize(25, 90))
        self.sadness.setMaximumSize(QtCore.QSize(25, 90))
        self.sadness.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(87,111,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(127,151,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(37,61,165);}\n"
"QSlider::groove:vertical:hover {background:rgba(87,111,215,0.25);}\n"
"QSlider::groove:vertical {background:rgba(87,111,215,0.15);}\n"
"\n"
"        ")
        self.sadness.setMaximum(3)
        self.sadness.setProperty("value", 0)
        self.sadness.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sadness.setInvertedAppearance(True)
        self.sadness.setObjectName("sadness")
        self.gridLayout_14.addWidget(self.sadness, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_15.setStyleSheet("")
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_14.addItem(spacerItem, 2, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_14.addItem(spacerItem1, 0, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/basicsblue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.tab_2)
        self.frame.setObjectName("frame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setHorizontalSpacing(18)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.victimhood = QtWidgets.QSlider(parent=self.frame)
        self.victimhood.setMinimumSize(QtCore.QSize(25, 90))
        self.victimhood.setMaximumSize(QtCore.QSize(25, 90))
        self.victimhood.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(153,153,255);}\n"
"QSlider::handle:vertical:hover {background:rgb(193,193,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(103,103,205);}\n"
"QSlider::groove:vertical:hover {background:rgba(153,153,255,0.25);}\n"
"QSlider::groove:vertical {background:rgba(153,153,255,0.15);}\n"
"\n"
"        ")
        self.victimhood.setMaximum(3)
        self.victimhood.setProperty("value", 0)
        self.victimhood.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.victimhood.setInvertedAppearance(True)
        self.victimhood.setObjectName("victimhood")
        self.gridLayout_13.addWidget(self.victimhood, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setStyleSheet("")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_13.addItem(spacerItem2, 0, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_13.addItem(spacerItem3, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/1 4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame1 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame1.setObjectName("frame1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(18)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_12 = QtWidgets.QLabel(parent=self.frame1)
        self.label_12.setStyleSheet("")
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 1, 1, 1, 1)
        self.pessimism = QtWidgets.QSlider(parent=self.frame1)
        self.pessimism.setMinimumSize(QtCore.QSize(25, 90))
        self.pessimism.setMaximumSize(QtCore.QSize(25, 90))
        self.pessimism.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(214,157,210);}\n"
"QSlider::handle:vertical:hover {background:rgb(254,197,250);}\n"
"QSlider::handle:vertical:pressed {background:rgb(164,107,160);}\n"
"QSlider::groove:vertical:hover {background:rgba(214,157,210,0.25);}\n"
"QSlider::groove:vertical {background:rgba(214,157,210,0.15);}\n"
"\n"
"        ")
        self.pessimism.setMaximum(3)
        self.pessimism.setProperty("value", 0)
        self.pessimism.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.pessimism.setInvertedAppearance(True)
        self.pessimism.setObjectName("pessimism")
        self.gridLayout_7.addWidget(self.pessimism, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 0, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 2, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame1, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/asfdasfasdfasdf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_19.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_5 = QtWidgets.QFrame(parent=self.tab_6)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(18)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.interest = QtWidgets.QSlider(parent=self.frame_5)
        self.interest.setMinimumSize(QtCore.QSize(25, 90))
        self.interest.setMaximumSize(QtCore.QSize(25, 90))
        self.interest.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(247,198,94);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,238,134);}\n"
"QSlider::handle:vertical:pressed {background:rgb(197,148,44);}\n"
"QSlider::groove:vertical:hover {background:rgba(247,198,94,0.25);}\n"
"QSlider::groove:vertical {background:rgba(247,198,94,0.15);}\n"
"\n"
"        ")
        self.interest.setMaximum(3)
        self.interest.setProperty("value", 0)
        self.interest.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.interest.setInvertedAppearance(True)
        self.interest.setObjectName("interest")
        self.gridLayout_8.addWidget(self.interest, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_16.setStyleSheet("")
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 0, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 2, 0, 1, 2)
        self.gridLayout_19.addWidget(self.frame_5, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/effort.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_6, icon3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_18.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_6 = QtWidgets.QFrame(parent=self.tab_7)
        self.frame_6.setMinimumSize(QtCore.QSize(45, 0))
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setHorizontalSpacing(18)
        self.gridLayout_9.setVerticalSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_9.addItem(spacerItem8, 0, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_17.setStyleSheet("")
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 1, 1, 1, 1)
        self.effort = QtWidgets.QSlider(parent=self.frame_6)
        self.effort.setMinimumSize(QtCore.QSize(25, 90))
        self.effort.setMaximumSize(QtCore.QSize(25, 90))
        self.effort.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(255,89,156);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,129,196);}\n"
"QSlider::handle:vertical:pressed {background:rgb(205,39,106);}\n"
"QSlider::groove:vertical:hover {background:rgba(255,89,156,0.25);}\n"
"QSlider::groove:vertical {background:rgba(255,89,156,0.15);}\n"
"\n"
"        ")
        self.effort.setMaximum(3)
        self.effort.setProperty("value", 0)
        self.effort.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.effort.setInvertedAppearance(True)
        self.effort.setObjectName("effort")
        self.gridLayout_9.addWidget(self.effort, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_9.addItem(spacerItem9, 2, 0, 1, 2)
        self.gridLayout_18.addWidget(self.frame_6, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/libidoHole.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_7, icon4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_7 = QtWidgets.QFrame(parent=self.tab_8)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(18)
        self.gridLayout_10.setVerticalSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_10.addItem(spacerItem10, 0, 0, 1, 2)
        self.decisiveness = QtWidgets.QSlider(parent=self.frame_7)
        self.decisiveness.setMinimumSize(QtCore.QSize(25, 90))
        self.decisiveness.setMaximumSize(QtCore.QSize(25, 90))
        self.decisiveness.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(120,155,172);}\n"
"QSlider::handle:vertical:hover {background:rgb(160,195,212);}\n"
"QSlider::handle:vertical:pressed {background:rgb(70,105,122);}\n"
"QSlider::groove:vertical:hover {background:rgba(120,155,172,0.25);}\n"
"QSlider::groove:vertical {background:rgba(120,155,172,0.15);}\n"
"\n"
"        ")
        self.decisiveness.setMaximum(3)
        self.decisiveness.setProperty("value", 0)
        self.decisiveness.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.decisiveness.setInvertedAppearance(True)
        self.decisiveness.setObjectName("decisiveness")
        self.gridLayout_10.addWidget(self.decisiveness, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_10.addItem(spacerItem11, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.frame_7, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/solitudeHole.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_8, icon5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_17.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_8 = QtWidgets.QFrame(parent=self.tab_9)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(18)
        self.gridLayout_11.setVerticalSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_11.addItem(spacerItem12, 0, 0, 1, 2)
        self.hygiene = QtWidgets.QSlider(parent=self.frame_8)
        self.hygiene.setMinimumSize(QtCore.QSize(25, 90))
        self.hygiene.setMaximumSize(QtCore.QSize(25, 90))
        self.hygiene.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(96,174,106);}\n"
"QSlider::handle:vertical:hover {background:rgb(136,214,146);}\n"
"QSlider::handle:vertical:pressed {background:rgb(46,124,56);}\n"
"QSlider::groove:vertical:hover {background:rgba(96,174,106,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(96,174,106,0.15);}\n"
"\n"
"        ")
        self.hygiene.setMaximum(3)
        self.hygiene.setProperty("value", 0)
        self.hygiene.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.hygiene.setInvertedAppearance(True)
        self.hygiene.setObjectName("hygiene")
        self.gridLayout_11.addWidget(self.hygiene, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_11.addItem(spacerItem13, 2, 0, 1, 2)
        self.gridLayout_17.addWidget(self.frame_8, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasdfasfsadfasf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_9, icon6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_9 = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setHorizontalSpacing(18)
        self.gridLayout_15.setVerticalSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.sexdrive = QtWidgets.QSlider(parent=self.frame_9)
        self.sexdrive.setMinimumSize(QtCore.QSize(25, 90))
        self.sexdrive.setMaximumSize(QtCore.QSize(25, 90))
        self.sexdrive.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(229,100,111);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,140,151);}\n"
"QSlider::handle:vertical:pressed {background:rgb(179,50,61);}\n"
"QSlider::groove:vertical:hover {background:rgba(229,100,111,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(229,100,111,0.15);}\n"
"\n"
"        ")
        self.sexdrive.setMaximum(3)
        self.sexdrive.setProperty("value", 0)
        self.sexdrive.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sexdrive.setInvertedAppearance(True)
        self.sexdrive.setObjectName("sexdrive")
        self.gridLayout_15.addWidget(self.sexdrive, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_15.addItem(spacerItem14, 0, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_20.setStyleSheet("")
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 1, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_15.addItem(spacerItem15, 2, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame_9, 0, 0, 1, 1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasfasfasfas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_4, icon7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_10 = QtWidgets.QFrame(parent=self.tab_5)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setHorizontalSpacing(18)
        self.gridLayout_16.setVerticalSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.solitude = QtWidgets.QSlider(parent=self.frame_10)
        self.solitude.setMinimumSize(QtCore.QSize(25, 90))
        self.solitude.setMaximumSize(QtCore.QSize(25, 90))
        self.solitude.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(223,133,93);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,173,133);}\n"
"QSlider::handle:vertical:pressed {background:rgb(173,83,43);}\n"
"QSlider::groove:vertical:hover {background:rgba(223,133,93,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(223,133,93,0.15);}\n"
"\n"
"        ")
        self.solitude.setMaximum(3)
        self.solitude.setProperty("value", 0)
        self.solitude.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.solitude.setInvertedAppearance(True)
        self.solitude.setObjectName("solitude")
        self.gridLayout_16.addWidget(self.solitude, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_14.setStyleSheet("")
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_16.addWidget(self.label_14, 1, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_16.addItem(spacerItem16, 2, 0, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_16.addItem(spacerItem17, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_10, 0, 0, 1, 1)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/Decisiveness.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_5, icon8, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_21.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_11 = QtWidgets.QFrame(parent=self.tab_10)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setHorizontalSpacing(18)
        self.gridLayout_20.setVerticalSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.guilt = QtWidgets.QSlider(parent=self.frame_11)
        self.guilt.setMinimumSize(QtCore.QSize(25, 90))
        self.guilt.setMaximumSize(QtCore.QSize(25, 90))
        self.guilt.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(170,129,224);}\n"
"QSlider::handle:vertical:hover {background:rgb(210,169,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(120,79,174);}\n"
"QSlider::groove:vertical:hover {background:rgba(170,129,224,0.25);}\n"
"QSlider::groove:vertical {background:rgba(170,129,224,0.15);}\n"
"\n"
"        ")
        self.guilt.setMaximum(3)
        self.guilt.setProperty("value", 0)
        self.guilt.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.guilt.setInvertedAppearance(True)
        self.guilt.setObjectName("guilt")
        self.gridLayout_20.addWidget(self.guilt, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_21.setStyleSheet("")
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_20.addWidget(self.label_21, 1, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_20.addItem(spacerItem18, 2, 0, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_20.addItem(spacerItem19, 0, 0, 1, 2)
        self.gridLayout_21.addWidget(self.frame_11, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, icon2, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_27.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.frame_2 = QtWidgets.QFrame(parent=self.tab_12)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setHorizontalSpacing(18)
        self.gridLayout_26.setVerticalSpacing(0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_26.addItem(spacerItem20, 0, 0, 1, 2)
        self.sleep = QtWidgets.QSlider(parent=self.frame_2)
        self.sleep.setMinimumSize(QtCore.QSize(25, 90))
        self.sleep.setMaximumSize(QtCore.QSize(25, 90))
        self.sleep.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(214,157,210);}\n"
"QSlider::handle:vertical:hover {background:rgb(254,197,250);}\n"
"QSlider::handle:vertical:pressed {background:rgb(164,107,160);}\n"
"QSlider::groove:vertical:hover {background:rgba(214,157,210,0.25);}\n"
"QSlider::groove:vertical {background:rgba(214,157,210,0.15);}\n"
"\n"
"        ")
        self.sleep.setMaximum(3)
        self.sleep.setProperty("value", 0)
        self.sleep.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sleep.setInvertedAppearance(True)
        self.sleep.setObjectName("sleep")
        self.gridLayout_26.addWidget(self.sleep, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_23.setStyleSheet("")
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_26.addWidget(self.label_23, 1, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_26.addItem(spacerItem21, 2, 0, 1, 2)
        self.gridLayout_27.addWidget(self.frame_2, 0, 0, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/Interest.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_12, icon9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_23.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_12 = QtWidgets.QFrame(parent=self.tab_11)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setHorizontalSpacing(18)
        self.gridLayout_22.setVerticalSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.outlook = QtWidgets.QSlider(parent=self.frame_12)
        self.outlook.setMinimumSize(QtCore.QSize(25, 90))
        self.outlook.setMaximumSize(QtCore.QSize(25, 90))
        self.outlook.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(200,129,224);}\n"
"QSlider::handle:vertical:hover {background:rgb(240,169,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(150,79,174);}\n"
"QSlider::groove:vertical:hover {background:rgba(200,129,224,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(200,129,224,0.15);}\n"
"\n"
"        ")
        self.outlook.setMaximum(3)
        self.outlook.setProperty("value", 0)
        self.outlook.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.outlook.setInvertedAppearance(True)
        self.outlook.setObjectName("outlook")
        self.gridLayout_22.addWidget(self.outlook, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_22.addItem(spacerItem22, 0, 0, 1, 2)
        self.label_22 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_22.setStyleSheet("")
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_22.addWidget(self.label_22, 1, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_22.addItem(spacerItem23, 2, 0, 1, 2)
        self.gridLayout_23.addWidget(self.frame_12, 0, 0, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/Victimhood.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/1 4.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_11, icon10, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setVerticalSpacing(0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.frame_3 = QtWidgets.QFrame(parent=self.tab_13)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_29.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_29.setHorizontalSpacing(12)
        self.gridLayout_29.setVerticalSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.altmans_summary_label = QtWidgets.QLabel(parent=self.frame_3)
        self.altmans_summary_label.setStyleSheet("font-weight:bold;margin-top:4px; margin-bottom:4px;")
        self.altmans_summary_label.setObjectName("altmans_summary_label")
        self.gridLayout_29.addWidget(self.altmans_summary_label, 1, 1, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout_29.addWidget(self.label, 0, 1, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_30.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_30.setSpacing(0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_13)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setSpacing(0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_31.addWidget(self.label_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_30.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame_13, 2, 1, 1, 2)
        self.beck_summary = QtWidgets.QSlider(parent=self.frame_3)
        self.beck_summary.setMinimumSize(QtCore.QSize(45, 110))
        self.beck_summary.setMaximumSize(QtCore.QSize(16777215, 110))
        self.beck_summary.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(244,56,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.35);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.25);}\n"
"\n"
"        ")
        self.beck_summary.setMaximum(36)
        self.beck_summary.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.beck_summary.setInvertedAppearance(True)
        self.beck_summary.setObjectName("beck_summary")
        self.gridLayout_29.addWidget(self.beck_summary, 0, 0, 3, 1)
        self.gridLayout_32.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_13, "")
        self.gridLayout_24.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.beckPage)
        self.altmanPage = QtWidgets.QWidget()
        self.altmanPage.setObjectName("altmanPage")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.altmanPage)
        self.gridLayout_46.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_46.setSpacing(0)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.tabWidget_2 = QtWidgets.QTabWidget(parent=self.altmanPage)
        self.tabWidget_2.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:3px;\n"
"\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.tabWidget_2.setIconSize(QtCore.QSize(11, 11))
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setMovable(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_28.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_28.setSpacing(0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.frame_14 = QtWidgets.QFrame(parent=self.tab_14)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_33.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_33.setHorizontalSpacing(18)
        self.gridLayout_33.setVerticalSpacing(0)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.altmans_sleep = QtWidgets.QSlider(parent=self.frame_14)
        self.altmans_sleep.setMinimumSize(QtCore.QSize(25, 110))
        self.altmans_sleep.setMaximumSize(QtCore.QSize(25, 110))
        self.altmans_sleep.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(87,111,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(127,151,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(37,61,165);}\n"
"QSlider::groove:vertical:hover {background:rgba(87,111,215,0.25);}\n"
"QSlider::groove:vertical {background:rgba(87,111,215,0.15);}\n"
"\n"
"        ")
        self.altmans_sleep.setMaximum(4)
        self.altmans_sleep.setTracking(True)
        self.altmans_sleep.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_sleep.setInvertedAppearance(True)
        self.altmans_sleep.setObjectName("altmans_sleep")
        self.gridLayout_33.addWidget(self.altmans_sleep, 1, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_33.addItem(spacerItem24, 2, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_24.setMinimumSize(QtCore.QSize(0, 110))
        self.label_24.setStyleSheet("")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_33.addWidget(self.label_24, 1, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_33.addItem(spacerItem25, 0, 0, 1, 2)
        self.gridLayout_28.addWidget(self.frame_14, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_14, icon, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.tab_15)
        self.gridLayout_34.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.frame_15 = QtWidgets.QFrame(parent=self.tab_15)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_35.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_35.setHorizontalSpacing(18)
        self.gridLayout_35.setVerticalSpacing(0)
        self.gridLayout_35.setObjectName("gridLayout_35")
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_35.addItem(spacerItem26, 2, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_25.setMinimumSize(QtCore.QSize(0, 110))
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout_35.addWidget(self.label_25, 1, 1, 1, 1)
        self.altmans_speech = QtWidgets.QSlider(parent=self.frame_15)
        self.altmans_speech.setMinimumSize(QtCore.QSize(25, 110))
        self.altmans_speech.setMaximumSize(QtCore.QSize(25, 110))
        self.altmans_speech.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(68,212,146);}\n"
"QSlider::handle:vertical:hover {background:rgb(108,252,186);}\n"
"QSlider::handle:vertical:pressed {background:rgb(18,162,96);}\n"
"QSlider::groove:vertical:hover {background:rgba(68,212,146,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(68,212,146,0.15);}\n"
"\n"
"        ")
        self.altmans_speech.setMaximum(4)
        self.altmans_speech.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_speech.setInvertedAppearance(True)
        self.altmans_speech.setObjectName("altmans_speech")
        self.gridLayout_35.addWidget(self.altmans_speech, 1, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_35.addItem(spacerItem27, 0, 0, 1, 2)
        self.gridLayout_34.addWidget(self.frame_15, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_15, icon6, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_36.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.frame_16 = QtWidgets.QFrame(parent=self.tab_16)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_37.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_37.setHorizontalSpacing(18)
        self.gridLayout_37.setVerticalSpacing(0)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.altmans_activity = QtWidgets.QSlider(parent=self.frame_16)
        self.altmans_activity.setMinimumSize(QtCore.QSize(25, 110))
        self.altmans_activity.setMaximumSize(QtCore.QSize(25, 110))
        self.altmans_activity.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(245,235,103);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,255,143);}\n"
"QSlider::handle:vertical:pressed {background:rgb(195,185,53);}\n"
"QSlider::groove:vertical:hover {background:rgba(245,235,103,0.25);}\n"
"QSlider::groove:vertical {background:rgba(245,235,103,0.15);}\n"
"        ")
        self.altmans_activity.setMaximum(4)
        self.altmans_activity.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_activity.setInvertedAppearance(True)
        self.altmans_activity.setObjectName("altmans_activity")
        self.gridLayout_37.addWidget(self.altmans_activity, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_37.addItem(spacerItem28, 2, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_26.setMinimumSize(QtCore.QSize(0, 110))
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_37.addWidget(self.label_26, 1, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_37.addItem(spacerItem29, 0, 0, 1, 2)
        self.gridLayout_36.addWidget(self.frame_16, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_16, icon3, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.tab_17)
        self.gridLayout_38.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.frame_17 = QtWidgets.QFrame(parent=self.tab_17)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_39.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_39.setHorizontalSpacing(18)
        self.gridLayout_39.setVerticalSpacing(0)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.label_27 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_27.setMinimumSize(QtCore.QSize(0, 110))
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_39.addWidget(self.label_27, 1, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_39.addItem(spacerItem30, 2, 0, 1, 2)
        self.altmans_cheer = QtWidgets.QSlider(parent=self.frame_17)
        self.altmans_cheer.setMinimumSize(QtCore.QSize(25, 110))
        self.altmans_cheer.setMaximumSize(QtCore.QSize(25, 110))
        self.altmans_cheer.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(255,161,92);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,201,132);}\n"
"QSlider::handle:vertical:pressed {background:rgb(205,111,42);}\n"
"QSlider::groove:vertical:hover {background:rgba(255,161,92,0.25);}\n"
"QSlider::groove:vertical {background:rgba(255,161,92,0.15);}\n"
"\n"
"        ")
        self.altmans_cheer.setMaximum(4)
        self.altmans_cheer.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_cheer.setInvertedAppearance(True)
        self.altmans_cheer.setObjectName("altmans_cheer")
        self.gridLayout_39.addWidget(self.altmans_cheer, 1, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_39.addItem(spacerItem31, 0, 0, 1, 2)
        self.gridLayout_38.addWidget(self.frame_17, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_17, icon7, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.tab_18)
        self.gridLayout_40.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.frame_18 = QtWidgets.QFrame(parent=self.tab_18)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_41.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_41.setHorizontalSpacing(18)
        self.gridLayout_41.setVerticalSpacing(0)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.altmans_confidence = QtWidgets.QSlider(parent=self.frame_18)
        self.altmans_confidence.setMinimumSize(QtCore.QSize(25, 110))
        self.altmans_confidence.setMaximumSize(QtCore.QSize(25, 110))
        self.altmans_confidence.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(199,76,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.15);}\n"
"\n"
"        ")
        self.altmans_confidence.setMaximum(4)
        self.altmans_confidence.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_confidence.setInvertedAppearance(True)
        self.altmans_confidence.setObjectName("altmans_confidence")
        self.gridLayout_41.addWidget(self.altmans_confidence, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_28.setMinimumSize(QtCore.QSize(0, 110))
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_41.addWidget(self.label_28, 1, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_41.addItem(spacerItem32, 2, 0, 1, 2)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_41.addItem(spacerItem33, 0, 0, 1, 2)
        self.gridLayout_40.addWidget(self.frame_18, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_18, icon4, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.tab_19)
        self.gridLayout_42.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_42.setHorizontalSpacing(18)
        self.gridLayout_42.setVerticalSpacing(0)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.frame_19 = QtWidgets.QFrame(parent=self.tab_19)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_43.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_43.setSpacing(0)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_44.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_44.setSpacing(0)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.frame_20)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 343, 185))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_45.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_45.setSpacing(0)
        self.gridLayout_45.setObjectName("gridLayout_45")
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_45.addItem(spacerItem34, 8, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_45.addWidget(self.label_3, 6, 0, 1, 2)
        self.altmans_summary_label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.altmans_summary_label_2.setStyleSheet("font-weight:bold;margin-top:4px; margin-bottom:4px;font-size:14pt;")
        self.altmans_summary_label_2.setObjectName("altmans_summary_label_2")
        self.gridLayout_45.addWidget(self.altmans_summary_label_2, 4, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_45.addWidget(self.label_4, 3, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_44.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.gridLayout_43.addWidget(self.frame_20, 2, 1, 1, 2)
        self.gridLayout_42.addWidget(self.frame_19, 1, 1, 1, 1)
        self.altmans_summary = QtWidgets.QSlider(parent=self.tab_19)
        self.altmans_summary.setMinimumSize(QtCore.QSize(45, 0))
        self.altmans_summary.setMaximumSize(QtCore.QSize(16777215, 110))
        self.altmans_summary.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(244,56,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.35);}\n"
"\n"
"        ")
        self.altmans_summary.setMaximum(20)
        self.altmans_summary.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_summary.setInvertedAppearance(True)
        self.altmans_summary.setObjectName("altmans_summary")
        self.gridLayout_42.addWidget(self.altmans_summary, 1, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_42.addItem(spacerItem35, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_19, "")
        self.gridLayout_46.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.altmanPage)
        self.beckDataPage = QtWidgets.QWidget()
        self.beckDataPage.setObjectName("beckDataPage")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.beckDataPage)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.beck_tableview = QtWidgets.QTableView(parent=self.beckDataPage)
        self.beck_tableview.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.beck_tableview.setShowGrid(False)
        self.beck_tableview.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.beck_tableview.setSortingEnabled(True)
        self.beck_tableview.setObjectName("beck_tableview")
        self.beck_tableview.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_25.addWidget(self.beck_tableview, 1, 0, 1, 1)
        self.hidemeframe = QtWidgets.QFrame(parent=self.beckDataPage)
        self.hidemeframe.setObjectName("hidemeframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hidemeframe)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.beck_time = QtWidgets.QTimeEdit(parent=self.hidemeframe)
        self.beck_time.setObjectName("beck_time")
        self.horizontalLayout.addWidget(self.beck_time)
        self.beck_date = QtWidgets.QDateEdit(parent=self.hidemeframe)
        self.beck_date.setObjectName("beck_date")
        self.horizontalLayout.addWidget(self.beck_date)
        self.gridLayout_25.addWidget(self.hidemeframe, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.beckDataPage)
        self.altmanDataPage = QtWidgets.QWidget()
        self.altmanDataPage.setObjectName("altmanDataPage")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.altmanDataPage)
        self.gridLayout_47.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_47.setSpacing(0)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.hidemeframe_2 = QtWidgets.QFrame(parent=self.altmanDataPage)
        self.hidemeframe_2.setObjectName("hidemeframe_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.hidemeframe_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.altman_time = QtWidgets.QTimeEdit(parent=self.hidemeframe_2)
        self.altman_time.setObjectName("altman_time")
        self.horizontalLayout_2.addWidget(self.altman_time)
        self.altman_date = QtWidgets.QDateEdit(parent=self.hidemeframe_2)
        self.altman_date.setObjectName("altman_date")
        self.horizontalLayout_2.addWidget(self.altman_date)
        self.gridLayout_47.addWidget(self.hidemeframe_2, 0, 0, 1, 1)
        self.altmans_manic_rating_table = QtWidgets.QTableView(parent=self.altmanDataPage)
        self.altmans_manic_rating_table.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.altmans_manic_rating_table.setShowGrid(False)
        self.altmans_manic_rating_table.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.altmans_manic_rating_table.setSortingEnabled(True)
        self.altmans_manic_rating_table.setObjectName("altmans_manic_rating_table")
        self.altmans_manic_rating_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_47.addWidget(self.altmans_manic_rating_table, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.altmanDataPage)
        self.gridLayout_12.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 454, 16))
        self.menubar.setObjectName("menubar")
        self.menuBECK = QtWidgets.QMenu(parent=self.menubar)
        self.menuBECK.setObjectName("menuBECK")
        self.menuViews = QtWidgets.QMenu(parent=self.menubar)
        self.menuViews.setObjectName("menuViews")
        self.menuData = QtWidgets.QMenu(parent=self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.actionCommit = QtGui.QAction(parent=MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionShowBeckExam = QtGui.QAction(parent=MainWindow)
        self.actionShowBeckExam.setObjectName("actionShowBeckExam")
        self.actionShowAltmanExam = QtGui.QAction(parent=MainWindow)
        self.actionShowAltmanExam.setObjectName("actionShowAltmanExam")
        self.actionShowBeckTable = QtGui.QAction(parent=MainWindow)
        self.actionShowBeckTable.setObjectName("actionShowBeckTable")
        self.actionShowAltmanTable = QtGui.QAction(parent=MainWindow)
        self.actionShowAltmanTable.setObjectName("actionShowAltmanTable")
        self.menuViews.addAction(self.actionShowBeckExam)
        self.menuViews.addAction(self.actionShowAltmanExam)
        self.menuViews.addAction(self.actionShowBeckTable)
        self.menuViews.addAction(self.actionShowAltmanTable)
        self.menuData.addAction(self.actionCommit)
        self.menuData.addAction(self.actionDelete)
        self.menubar.addAction(self.menuBECK.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.beck_summary.valueChanged['int'].connect(self.altmans_summary_label.setNum) # type: ignore
        self.altmans_summary.valueChanged['int'].connect(self.altmans_summary_label_2.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Today, I do not feel sad.</p><p>Today, I feel sad.</p><p>Today, I feel sad all the time and can\'t snap out of it.</p><p>Today, I feel so sad and unhappy that I can\'t stand it.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sadness"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Today, I don’t feel I am being punished.</p><p>Today, I feel I may be punished.</p><p>Today, I expect to be punished.</p><p>Today, I feel I am being punished.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "victimhood"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>I don\'t feel disappointed in myself. </p><p>I am disappointed in myself.</p><p>I am disgusted with myself.</p><p>I hate myself.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "pessimism"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Today, I get as much satisfaction out of things as I used to.</p><p>Today, I don’t enjoy things the way I used to.</p><p>Today, I don\'t get real satisfaction out of anything anymore.</p><p>Today, I am dissatisfied or bored with everything.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "interest"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Today, I can work about as well as before.</p><p>Today, it takes extra effort to get started doing something.</p><p>Today, I have to push myself very hard to do anything.</p><p>Today, I can\'t do any work at all.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "effort"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>Today, I make decisions about as well as I ever could.</p><p>Today, I put off making decisions more than I used to.</p><p>Today, I have greater difficulty in making decisions than I used to.</p><p>Today, I can\'t make decisions at all anymore.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "decisiveness"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Today, I don’t feel that I look any worse than I used to.</p><p>Today, I am worried that I am looking old or unattractive.</p><p>Today, I am gross without redemption.</p><p>Today, I believe that I look ugly.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "hygiene"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Today, I have not noticed any recent changes in my interest in sex.</p><p>Today, I am less interested in sex than I used to be.</p><p>Today, I have almost no interest in sex.</p><p>Today, I have lost interest in sex completely.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "sexdrive"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Today, I have not lost interest in other people.</p><p>Today, I am less interested in other people than I used to be.</p><p>Today, I have lost most of my interest in other people.</p><p>Today, I have lost all of my interest in other people.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "isolated"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Today, I do not feel like a failure.</p><p>Today, I feel I have failed more than the average person.</p><p>Today, when I look back on my life, all I see are failures.</p><p>Today, I feel I am a complete failure as a person.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "guilt"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Last night, I slept as well as usual.</p><p>Last night, I didn\'t sleep as well as I used to.</p><p>Last night, I slept more than I usually do</p><p>I slept far too long to be considered even remotely healthy. </p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "sleep"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>Today, I am not particularly discouraged about the future.</p><p>Today, I feel discouraged about the future.</p><p>Today, I feel I have nothing to look forward to.</p><p>Today, I feel the future is hopeless and that things cannot improve.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "prospects"))
        self.altmans_summary_label.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">How Depo\'d Are You?</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">1-10 :</span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\"> These ups and downs are considered normal </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">11-16 </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">: Mild mood disturbance </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">17-20 </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">: Borderline clinical depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">21-30 : </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">Moderate depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">31-40 : </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">Severe depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">over 40 : </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">Extreme depression </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "sum"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>Usual 7-8 hours, needed.</p><p><span style=\" font-size:10pt;\">I needed less sleep than usual and still functioned well.</span></p><p>6 hours or less slept feels like 8</p><p>Debating pulling an all nighter.</p><p>Pulled an all nighter and do not feel it as bad as I should.</p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>I speak normal, for me.</p><p><span style=\" font-size:10pt;\">Stumbling over words due to having too many at once.</span></p><p>Getting annoying, talking over others, quicker speech.</p><p>Talking more, talking faster, making sense still</p><p><span style=\" font-size:10pt;\">Salad of word.</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>I am not more active (socially, sexually, work, home) than usual</p><p>I have been a little more active than usual</p><p>I am noticeably more active and for longer today</p><p>I am far more active than usual.</p><p>I cannot stop moving nor doing. </p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Base level of cheeriness</span></p><p>Feeling happier or more cheeful than usual</p><p>Feeling happier and more cheerful, significantly.</p><p>I\'m ecstatic </p><p>I\'m annoying in my positivity. </p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Base level of confidence</span></p><p>Feeling more confident than usual today.</p><p>Feeling more confident for longer than usual today.</p><p>Confidence bordering on delusion</p><p>Delusional.</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">• A cutoff score of 6 </span>or higher indicates a high probability of a manic or hypomanic condition (based on a sensitivity rating of 85.5% and a specificity rating of 87.3%).</p><p><span style=\" font-weight:600;\">• A score of 6 </span>or higher may indicate a need for treatment and/or further diagnostic workup to confirm a diagnosis of mania or hypomania.</p><p><span style=\" font-weight:600;\">• A score of 5</span> or lower is less likely to be associated with significant symptoms of mania.</p></body></html>"))
        self.altmans_summary_label_2.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">How Manic Are You?</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_19), _translate("MainWindow", "sum"))
        self.beck_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.beck_date.setDisplayFormat(_translate("MainWindow", "yyyy/mm/dd"))
        self.altman_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.altman_date.setDisplayFormat(_translate("MainWindow", "yyyy/mm/dd"))
        self.menuBECK.setTitle(_translate("MainWindow", "Beck | Altman"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.actionCommit.setText(_translate("MainWindow", "Commit Beck and Altman Exams"))
        self.actionCommit.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionDelete.setText(_translate("MainWindow", "Delete Selected Record(s)"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionShowBeckExam.setText(_translate("MainWindow", "Beck Exam"))
        self.actionShowBeckExam.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionShowAltmanExam.setText(_translate("MainWindow", "Altman Exam"))
        self.actionShowAltmanExam.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionShowBeckTable.setText(_translate("MainWindow", "Beck Data View"))
        self.actionShowBeckTable.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.actionShowAltmanTable.setText(_translate("MainWindow", "Altman Data View"))
        self.actionShowAltmanTable.setShortcut(_translate("MainWindow", "Ctrl+4"))
